call dart run vector_graphics_compiler -i assets/0.svg -o assets/0.svg.vec
call dart run vector_graphics_compiler -i assets/1.svg -o assets/1.svg.vec
call dart run vector_graphics_compiler -i assets/2.svg -o assets/2.svg.vec
call dart run vector_graphics_compiler -i assets/3.svg -o assets/3.svg.vec
call dart run vector_graphics_compiler -i assets/4.svg -o assets/4.svg.vec
call dart run vector_graphics_compiler -i assets/5.svg -o assets/5.svg.vec
call dart run vector_graphics_compiler -i assets/6.svg -o assets/6.svg.vec
call dart run vector_graphics_compiler -i assets/7.svg -o assets/7.svg.vec
call dart run vector_graphics_compiler -i assets/8.svg -o assets/8.svg.vec
call dart run vector_graphics_compiler -i assets/9.svg -o assets/9.svg.vec
call dart run vector_graphics_compiler -i assets/10.svg -o assets/10.svg.vec
call dart run vector_graphics_compiler -i assets/11.svg -o assets/11.svg.vec
call dart run vector_graphics_compiler -i assets/12.svg -o assets/12.svg.vec
call dart run vector_graphics_compiler -i assets/13.svg -o assets/13.svg.vec
call dart run vector_graphics_compiler -i assets/14.svg -o assets/14.svg.vec
call dart run vector_graphics_compiler -i assets/15.svg -o assets/15.svg.vec
call dart run vector_graphics_compiler -i assets/16.svg -o assets/16.svg.vec
call dart run vector_graphics_compiler -i assets/17.svg -o assets/17.svg.vec
call dart run vector_graphics_compiler -i assets/18.svg -o assets/18.svg.vec
