name: shape_shifter_icon_example
description: Demonstrates how to use the shape_shifter_icon package.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shape_shifter_icon: ^1.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  vector_graphics_compiler: ^1.1.14

dependency_overrides:
  shape_shifter_icon:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/