name: shape_shifter_icon
description: Fully animated icons.
version: 1.0.0
homepage: https://github.com/deakjahn/shape_shifter_icon

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.14
  vector_graphics: ^1.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true